grpc:
  port: 7080
  security:
    cert-chain: serverCert.pem
    private-key: serverKey.pem

spring:
  application:
    name: example-server
  datasource:
    username: postgres
    password: changeit
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    user:
      password: password
      name: user
      roles: USER
